

server:
  port: 8050

spring:
  application:
    name: gateway-service
  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka
  cloud:
    gateway:
      routes:
        - id: accountRoute
          uri: lb://account-service
          predicates:
            - Path=/accounts/**
        - id: userRoute
          uri: lb://user-service
          predicates:
            - Path=/users/**
        - id: transactionRoute
          uri: lb://transaction-service
          predicates:
            - Path=/transactions/**

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

management:
  endpoints:
    web:
      exposure:
        include: '*'
